services:
  database_service:
    image: postgres:18

    # Container name for easier debugging in docker tools
    container_name: chessforge_database_container

    # Database configuration
    # Credentials are used to initialize to database
    # Same credentials are hardcoded in connections.py so that app service can connect
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: 123456 # Does not matter for local-only dev tool
      POSTGRES_DB: chessforge_database

    # Exposes DB to host machine (useful for tools like DBeaver)
    ports:
      - "5432:5432"

    # Persistent storage so PostgreSQL data created in container survives container shutdowns
    volumes:
      - database_data:/var/lib/postgresql # not '/var/lib/postgresql/data' like in earlier postgres versions


  app:
    build: .

    # Mount local data folder inside container
    volumes:
      - ./data:/app/data

    # Ensure database starts before app container
    depends_on:
      - database_service


# Named Docker volume used to persist PostgreSQL data
volumes:
  database_data: